version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 038462757595.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t aws-ecs-tilak-ecr .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag aws-ecs-tilak-ecr:latest 038462757595.dkr.ecr.ap-south-1.amazonaws.com/aws-ecs-tilak-ecr:latest
      - echo Pushing the Docker image to ECR...
      - docker push 038462757595.dkr.ecr.ap-south-1.amazonaws.com/aws-ecs-tilak-ecr:latest

artifacts:
  files:
    - '**/*'
